### PR TITLE
Restore EnsureAotCompatibility test

### PR DESCRIPTION
**Pull request by kllysng**
The test is passing locally without issue. Running an ADO PR build to ensure it passes there too.

Update - test passed in ADO build with no issues, running again

Update again - passed again

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]

**Comment by msbw2** [comment]
I think this might be a build step. At least it would make sense to be one to me instead of a unit test.

**Comment by keegan-caruso** [comment]
> I think this might be a build step. At least it would make sense to be one to me instead of a unit test.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/90dfd314cf39f40aae8f23a51155762d91c3416c/build/common.props#L78

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @kellyyangsong 

Do we understand why it was skipped in the first place?

**Comment by kllysng** [comment]
> LGTM Thanks @kellyyangsong
> 
> Do we understand why it was skipped in the first place?

@jmprieur yes, thanks for asking, I should have explained in a comment. It was skipped because it would timeout which for this test is taking longer than 3 min in the ADO build. I re-ran this many times and never saw it take longer than 50s to complete.

**Comment by kllysng** [comment]
> I think this might be a build step. At least it would make sense to be one to me instead of a unit test.


> > I think this might be a build step. At least it would make sense to be one to me instead of a unit test.
> 
> https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/90dfd314cf39f40aae8f23a51155762d91c3416c/build/common.props#L78

We have an analyzer that will cause warnings - but I still think this test is useful until we start treating warnings as errors.

**Pull request merged**
