### PR TITLE
fix WsUtility ns

### PR DESCRIPTION
**Pull request by 616b2f**
fix: #1119

### CODE REVIEW

**Comment by mafurman** [comment]
@616b2f Could you please squash your commits and issue this PR against our dev5x branch?

**Comment by 616b2f** [comment]
@mafurman done. First I messed it up with changing the base to dev5x and have to force push 2 times, but now it looks good :)

**Comment by mafurman** [comment]
@616b2f Thanks! :) I just merged in your PR.

**Pull request merged**
