### PR TITLE
Add ConfigureAwait for await to avoid deadlock

### PR DESCRIPTION
**Pull request by ChenYan98**
#301

### CODE REVIEW

**Comment by brentschmaltz** [comment]
:shipit:

**Comment by tushargupta51** [comment]
@ChenYan98 Have you compared 4.x and 5.x to make sure we have covered all the places where we should add the configureAwait?

**Comment by brentschmaltz** [comment]
We had just missed those two.

:shipit:

**Comment by ChenYan98** [comment]
@tushargupta51 @brentschmaltz Actually, I found we do missed this one on 5.x: await _refreshLock.WaitAsync(cancel); but I am not sure if it is good time to fix it now. Could you make decision?

**Comment by brentschmaltz** [comment]
We need separate PR for KDev. I will merge this into 4.x

**Pull request merged**
