### PR TITLE
Issue: AzureAD#1107

### PR DESCRIPTION
**Pull request by gislikonrad**
Adds support for jwt tokens enveloped in BinarySecurityToken XML elements.

### CODE REVIEW

**Comment by gislikonrad** [comment]
The base64 encoding was missing from the original fix. I added it, rebased and squashed.

There was also a LogMessage added with error code **IDX12707** that is derived from **IDX10707** in the old JwtSecurityTokenHandler.

**Comment by brentschmaltz** [comment]
@gislikonrad apologies for the delay, we will take this in the 6.7.3 release

**Comment by brentschmaltz** [comment]
@gislikonrad  i am going to rebase this and see if we can fit it in.

**Comment by brentschmaltz** [comment]
@gislikonrad closing as this doesn't fit in our product plans.

**Pull request closed without merging**
