### PR TITLE
Set the IssuerSigningKeyResolverUsingConfiguration Delegate in the Clone() Method

### PR DESCRIPTION
**Pull request by dannybtsai**
The IssuerSigningKeyResolverUsingConfiguration property should be copied in the Clone() method.

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Comment by jennyf19** [comment]
are there any tests which need to be updated?

**Review by RojaEnnam — APPROVED** [review]

**Comment by jennyf19** [comment]
@brentschmaltz and @dannybtsai when I approved there was just a one line change...

**Review by jennyf19 — CHANGES_REQUESTED** [review]
removign previous approval

**Comment by jmprieur** [comment]
@dannybtsai : this branch has merge conflicts and seem to have an enormous amount of changes (whereas the description of the PR seems to be a one line change?)

Is this expected?
@brentschmaltz ?

**Comment by dannybtsai** [comment]
@jmprieur, I think Brent rebased on to dev earlier, this is no longer needed. Sorry for the confusion, closing this now.

**Pull request closed without merging**
