### PR TITLE
Fix bug in WebKeySet deserialization

### PR DESCRIPTION
**Pull request by hanabi1224**
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/901 
https://github.com/JamesNK/Newtonsoft.Json/issues/703

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@hanabi1224 Thanks for the fix. I am concerned about the static in the test as sometimes we have issues with parallel tests. How about adding an overload to JsonWebKeySet(string, JsonSerializerSettings).

**Comment by hanabi1224** [comment]
@brentschmaltz  Do you mean overloading the constructor of JsonWebKeySet or JsonWekKeySetDataSet in test method?

BTW, if this static setting causes flakiness to other test cases, it might indicate there're similar bugs in other places.

**Comment by brentschmaltz** [comment]
@hanabi1224 Overloading the JsonWebKeySet. In general, statics have given us some pain when running tests in parallel. With the overload to JsonWebKeySet, we could test it out without affecting other tests.

**Comment by hanabi1224** [comment]
@brentschmaltz  Can you please elaborate? I don't quite understand, is it a constructor only for tests?  And what if we want to test  OpenIdConnectConfigurationRetriever, it's directly calling openIdConnectConfiguration.JsonWebKeySet = JsonConvert.DeserializeObject(keys);   how would it help by overloading JsonWebKeySet constructor?

**Comment by brentschmaltz** [comment]
@hanabi1224  If we don't have the instance control and we rely on the static, the entire application and all code in the call graph would be affected if someone wants to Deserialize a JsonWebKeySet using a specific setting. This insulates the call graph to just the one call. Calls to OpenIdConnectConfigurationRetriever is another issue. In fact, we may want to think about how other types perform serialization.

**Comment by hanabi1224** [comment]
@brentschmaltz  I think this bug is essentially caused by improper usage of Json.Net (setter should always be supplied for JsonProperty) and has nothing to do with instance control of JsonConvertSettings, that's why I'm not convinced to change JsonWebKeySet constructor, your proposal sounds like a different way of fixing the problem, keep improper usage of Json.Net and always use a good JsonConvertSetting that happen to work.

**Comment by brentschmaltz** [comment]
@hanabi1224 no, not at all. We should have the private setter, I thank you for bringing that to our attention.
I am working on the presumption that it may be the case a user wants to use a specific JsonSerializerSettings for an object as that gives finer grained control. Something I think would add benefit for a library.
As for testing, if you can't test a library, you really don't have a library. Which means it has to be developed so it can be tested.
I have found global static properties cause test issues and result in serializing tests.

**Comment by hanabi1224** [comment]
@brentschmaltz  I have updated PR as u suggested, can you plz take another look?

**Comment by hanabi1224** [comment]
@brentschmaltz  PR updated

**Comment by brentschmaltz** [comment]
@hanabi1224 thanks!
We'll pull it in.

**Pull request merged**
