### PR TITLE
Add CancellationToken for ValidateTokenAsync

### PR DESCRIPTION
**Pull request by RojaEnnam**
Adds CancellationToken to ValidateTokenAsync  API. #2451

### CODE REVIEW

**Review by ciaozhang — APPROVED** [review]

**Review by westin-m — APPROVED** [review]

**Review by westin-m — COMMENTED** [review]
waiting for a solution to virtual method throwing an exception in abstract class

**Comment by keegan-caruso** [comment]
pls rebase off of dev. I expect this to fail on baseline package validation.

**Review by keegan-caruso — CHANGES_REQUESTED** [review]
will likely fail baseline package validation.

**Comment by keegan-caruso** [comment]
I was wrong, it isn't failing, I guess because of the default implementation. But this is still breaking at runtime.

**Pull request closed without merging**
