### PR TITLE
#1680 ValidateHash method Alg is null when token is an jwe token 

### PR DESCRIPTION
**Pull request by jxnkwlp**
#1680 ValidateHash method Alg is null when token is an jwe token

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet?pullRequest=1692) <br/>All CLA requirements met.

**Review by jennyf19 — COMMENTED** [review]
are there tests to update/add?

**Comment by jxnkwlp** [comment]
> are there tests to update/add?

yeah... i will add tests in these days .

**Comment by brentschmaltz** [comment]
@jxnkwlp it's odd that the token is a JWE.
Where is this being called from?

**Comment by brentschmaltz** [comment]
@jxnkwlp this fell off the radar, would like to pull it in but we need to have it rebased against dev.

**Comment by jxnkwlp** [comment]
Okay, working on it

**Review by jennyf19 — APPROVED** [review]
:shipit: 
@brentschmaltz Please review and merge

**Comment by brentschmaltz** [comment]
@jxnkwlp thanks.

**Comment by jennyf19** [comment]
Thank you for the contribution @jxnkwlp. this will be in our next release (either 6.19.1 or 6.20).

**Pull request merged**
