### PR TITLE
Add additional metadata parameters to OpenIdConnectConfiguration

### PR DESCRIPTION
**Pull request by ghost**
Some metadata parameters are missing in `OpenIdConnectConfiguration`:

- `authorization_encryption_alg_values_supported`, `authorization_encryption_enc_values_supported`, and `authorization_signing_alg_values_supported` from [JWT Secured Authorization Response Mode for OAuth 2.0 (JARM)](https://openid.net/specs/oauth-v2-jarm.html)
- `tls_client_certificate_bound_access_tokens` from [OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens](https://datatracker.ietf.org/doc/html/rfc8705)

This PR adds them.

### CODE REVIEW

**Review by brentschmaltz — APPROVED** [review]
thanks!

**Comment by ghost** [comment]
Hum, the failure in CI seems unrelated.

**Comment by brentschmaltz** [comment]
@joegoldman2 yep, failure doesn't seem related.
Will rerun.

**Comment by brentschmaltz** [comment]
@joegoldman2 rerun succeeded, this will be in preview6.

**Pull request merged**
