### PR TITLE
Reduce allocations of byte arrays

### PR DESCRIPTION
**Pull request by lechu445**
MemoryStream.ToArray() allocates a new array on heap if contain any data. Due to the fact that we operate on MemoryStream (it's just a wrapper on byte array buffer) we can access to the internal buffer directly by using GetBuffer method.

@brentschmaltz

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@lechu445 are you OK with me manually adding this code and closing this as i have rebased and squashed in this topic branch?

Thanks for suggesting this change.

**Comment by brentschmaltz** [comment]
@lechu445 could you rebase this and target the dev branch?

**Comment by lechu445** [comment]
@brentschmaltz done

**Review by brentschmaltz — APPROVED** [review]

**Comment by brentschmaltz** [comment]
@lechu445  merged, thanks.

**Pull request merged**
