### PR TITLE
Changes the default implementation of CanWriteSecurityToken

### PR DESCRIPTION
**Pull request by gislikonrad**
Changes the default implementation of CanWriteSecurityToken in SecurityTokenHandler to ensure backwards compatibility.

It was only implemented in Saml2SecurityTokenHandler, so no other AzureAD SecurityTokenHandlers are able to be used in a RequestSecurityTokenResponse without being inherited and overridden.

### CODE REVIEW

**Comment by gislikonrad** [comment]
@brentschmaltz

**Comment by gislikonrad** [comment]
Do you want a bug to accompany this PR?

**Comment by brentschmaltz** [comment]
@gislikonrad i am seeing 200 files modified. Can you rebase against dev and resubmit?

**Comment by gislikonrad** [comment]
The code changes the default implementation of CanWriteSecurityToken that is only in the wstrust branch, so I can't rebase againt dev.

**Comment by brentschmaltz** [comment]
@gislikonrad my bad, i incorrectly assumed dev :-)

**Comment by brentschmaltz** [comment]
@gislikonrad I'm thinking the Saml2SecurityTokenHandler should be modified use this new default.
I will pull in your commit and make some changes. I'll include you on the PR review.

**Comment by brentschmaltz** [comment]
@gislikonrad we ran out of time, will get this in the July release.

We need to make sure we have the right tests.

**Comment by gislikonrad** [comment]
I'm looking forward to the WS-TRUST release. 👍

**Comment by gislikonrad** [comment]
@brentschmaltz Is this something that is still being considered? If so, I can rebase and clean up the source branch.

**Comment by gislikonrad** [comment]
Issue auto-closed when I was cleaning up the branch... Had some merges that I wanted to get rid of so I could rebase instead. Issue has been reopened.

**Comment by brentschmaltz** [comment]
We were unable to get this in time and it's too far out of date.
We are sorry, but we didn't have the resources.
We do now.

**Pull request closed without merging**
