### PR TITLE
Adding extensibility for IsSupportedAlgorithm method

### PR DESCRIPTION
**Pull request by tushargupta51**
@brentschmaltz @polita @pinpointtownes

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Curious: any particular to not reuse `AsymmetricAlgorithmResolver`? (we'd also need a `SymmetricAlgorithmResolver` btw)

Isn't your `IsSupportedAlgorithm` semantically similar to `var isSupported = AsymmetricAlgorithmResolver(algorithm) != null`?

**Comment by tushargupta51** [comment]
@PinpointTownes Both delegates provide different knobs. `IsSupportedAlgorithm` allows users to control algorithms names that runtime understands. For example, they can add a new alg name that creates an `RSA` instance. They don't have to worry about returning an `RSA` instance, just hook up the `IsSupportedAlgorithm` and return true for that string.

If users hook up `AsymmetricAlgorithmResolver` to support `AsymmetricAlgoritm` that runtime does not create by default, they don't need to override the `IsSupportedAlgorithm`.

**Comment by ChenYan98** [comment]
Issue: #404

**Comment by PinpointTownes** [comment]
@tushargupta51 sure, but the two are closely linked: if `IsSupportedAlgorithm` returns `true`, then `GetAsymmetricAlgorithm` must return a non-null value.

If you use a different extensibility hook for `IsSupportedAlgorithm` and `GetAsymmetricAlgorithm`, then there's a risk that a user will set up a `IsSupportedAlgorithm` delegate returning `true` but won't provide an `AsymmetricAlgorithmResolver` delegate. In this case, `GetAsymmetricAlgorithm` might return a null value, even if `IsSupportedAlgorithm` returns `true`.

My suggestion was to adopt something similar to IM 4.5, that relies on `CryptoHelper.GetAlgorithmFromConfig`:

```csharp
public override bool IsSupportedAlgorithm(string algorithm) {
    if (string.IsNullOrEmpty(algorithm)) {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgument(algorithm, SR.GetString(SR.EmptyOrNullArgumentString, "algorithm"));
    }

    object algorithmObject = null;

    try {
        algorithmObject = CryptoHelper.GetAlgorithmFromConfig(algorithm);
    }
    catch (InvalidOperationException) {
        algorithmObject = null;
    }

    if (algorithmObject != null) {
        SignatureDescription signatureDescription = algorithmObject as SignatureDescription;
        if (signatureDescription != null)
            return true;
        AsymmetricAlgorithm asymmetricAlgorithm = algorithmObject as AsymmetricAlgorithm;
        if (asymmetricAlgorithm != null)
            return true;
        return false;
    }

    switch (algorithm) {
    case SecurityAlgorithms.RsaV15KeyWrap:
    case SecurityAlgorithms.RsaOaepKeyWrap:
    case SecurityAlgorithms.RsaSha1Signature:
    case SecurityAlgorithms.RsaSha256Signature:
        return true;
    default:
        return false;
    }
}
```

**Comment by tushargupta51** [comment]
@PinpointTownes I wanted to stay away from calling the `AsymmetricAlgorithmResolver` in `IsSupportedAlgorithm` method because of its possible time complexity to create actual algorithms. In case of CryptoHelper, since there is an underlying map between string alg and alg object, it might not be so bad.

But I realized that people will have to follow these steps if they want to add custom algorithms:
1. Create a CPF and hook up CPF.AsymmetricAlgorithmResolver.
2. Set SecurityKey.CPF to the one created above.
3. Set CPF.IsSupportedAlgorithm to return true for the new alg.

Although without doing 3, users can still call `key.GetSignatureProvider` and it will return the custom `AsymmetricAlgorithm` object, it will be confusing and error prone if they rely on results of `key.IsSupportedAlgorithm` before calling `key.GetSignatureProvider`. 

Keeping these in mind, I updated the code acc to your suggestion. `IsSupportedAlgorithm` will call the delegate and returns true if delegate returns a non-null object. If it is null, it fall back to default checks and compare input alg against default algorithms. This removes step 3 in the process above.

I also added a `SymmetricAlgorithmResolver` delegate.

**Comment by PinpointTownes** [comment]
Fantastic, exactly what I had in mind :clap: 

One question though: is there any particular reason to limit `SymmetricAlgorithmResolver` to `KeyedHashAlgorithm` instances? Supporting MAC algorithms is great, but probably not enough: one won't be able to return an encryption algorithm (e.g AES/TripleDES). Why not just returning `SymmetricAlgorithm`?

**Comment by tushargupta51** [comment]
@PinpointTownes I initially had `SymmetricAlgorithm` but later dropped it since that does not support returning hash algorithms like MD5 or SHA256. I had to choose between `HashAlgorithm` and `SymmetricAlgorithm` as the return type since they do not have a common parent. Also, I chose `KeyedHashAlgorithm` instead of `HashAlgorithm` because we are doing key based hashing.

**Comment by PinpointTownes** [comment]
Shouldn't we just have a separate `HashAlgorithmResolver`?

**Comment by tushargupta51** [comment]
@PinpointTownes I see that the name of the delegate is misleading. It should be `HashAlgorithmResolver` or 'KeyedHashAlgorithmResolver`. The intention here is to allow users to hook up their own keyed hash algorithm. Plugging in a `SymmetricAlgorithm` won't help with sign/verify operations as it does not support those.

**Comment by PinpointTownes** [comment]
> I see that the name of the delegate is misleading. It should be HashAlgorithmResolver or 'KeyedHashAlgorithmResolver.

Yep. That said, you'll also need a `SymmetricAlgorithmResolver` returning a `SymmetricAlgorithm` at some point (when implementing JWE or when adding back SAML), so maybe it's not harmful to have the 3 hooks in place right now.

**Comment by tushargupta51** [comment]
@PinpointTownes I agree we need those delegates when we have the encryption support in. Though, it makes more sense to add those hooks when we add the encryption feature.

**Comment by brentschmaltz** [comment]
@PinpointTownes as you said
>My suggestion was to adopt something similar to IM 4.5, that relies on >CryptoHelper.GetAlgorithmFromConfig:

It would be ideal if extensibility was opaque to IdentityModel. CryptoConfig is absent from CoreFx so we need something internal to IM. CryptoFactory may be a nature place for such extensibility. Although it would need to be 'global' to the app.

thoughts?

**Comment by tushargupta51** [comment]
@PinpointTownes The problem with the delegate resolvers is that it's not easy to add a support for just one algorithm. Since we skip the default algorithm resolution logic if a delegate is set by the user and if the delagate returns null, we throw.

We were evaluating if its better to have something similar to `CryptoConfig.AddAlgorithm(Type, String[])` instead of delagates. We will add static methods on `CryptoProviderFactory`:
1. `AddAsymmetricAlgorithm(String[], AsymmetricAlgorithm)`
2. `AddKeyedHashAlgorithm(String[], KeyedHashAlgorithm)`

And these methods will maintain a mapping internally. The benefit here is that users do not have to ensure that the default behavior (creating RSA, ECDSA) is also present in the delegate resolvers.

**Comment by PinpointTownes** [comment]
Sure, a dictionary is a good option too (I'm pretty sure I had suggested it before the resolver delegate was introduced). That said, why making that completely static?

**Comment by tushargupta51** [comment]
I don't see the use case where users will need to set the mapping from a string alg to an alg obj per CPF. Setting it once and using the same object type in future whenever the new "alg" string is found seems like the right thing to do.

**Comment by brentschmaltz** [comment]
@tushargupta51 @PinpointTownes sounds like we agreement that this type of extensibility makes sense. Another reason for the static is OpenIdConnectProtocolValidator could reach out for custom algorithms across OS's. When validating the c_hash or at_hash we need to map the 'alg' in the header to a HashAlg. Currently, OIDCPV knows nothing about a CryptoProviderFactory instance. 
A good instance solution would start with the static defaults and them be configurable per instance something like the JwtSecurityTokenHandler claim mapping (that everyone loves :-)

**Comment by PinpointTownes** [comment]
> I don't see the use case where users will need to set the mapping from a string alg to an alg obj per CPF. 

Well, the same reasoning could be applied to the signature provider. IMHO, it's probably better to be consistent here.

> Another reason for the static is OpenIdConnectProtocolValidator could reach out for custom algorithms across OS's.

Sure, but nothing prevents you from adding a `CryptoProviderFactory` property in this class. If none is explicitly provided, the default `CryptoProviderFactory.Default` static instance is used as a fallback. The resolvers/mappings properties don't have to be static for that.

**Comment by tushargupta51** [comment]
Closing this PR as the changes here are subset of #444 .

**Pull request closed without merging**
