### PR TITLE
using openssl when running on unix/coreclr

### PR DESCRIPTION
**Pull request by tushargupta51**
Fixing #324. I am not changing ECDsa to use OpenSSL yet since that requires updating ECDsaSecurityKey to work on unix (#325). Will come to that later.

### CODE REVIEW

**Comment by tushargupta51** [comment]
@brentschmaltz

**Comment by PinpointTownes** [comment]
It looks fine as a temporary fix, but you should definitely consider updating `RsaSecurityKey`'s constructor to take a `RSA` instance instead of creating one in the signature provider.

**Comment by PinpointTownes** [comment]
:shipit:

**Comment by ericstj** [comment]
@bartonjs don't we have a cross-plat type for RSACng/RSAOpenSsl?

The current implementation will cause the JIT to hit the OpenSSL assembly, even on Windows.  That won't work in the future.

The only reason this may work today is because we've delayed the packaging changes to move these platform specific libraries to platform specific folders in the packages.  We're delaying that work because folks cannot yet represent platform-specific dependencies in nuget/project.json.  https://github.com/dotnet/cli/issues/465 https://github.com/NuGet/Home/issues/1660

**Comment by bartonjs** [comment]
@ericstj We didn't 10 days ago, no.  But https://github.com/dotnet/corefx/issues/2953 was fixed 2 days ago (which @PinpointTownes celebrated).

So this particular change can be switched to using RSA.Create() now, and there'll be a couple of builds overlap between RSA.Create() existing and the OpenSsl package going back to registered as unix-only (https://github.com/dotnet/corefx/issues/6046).

**Pull request merged**
