### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by brentschmaltz**
Refactor into separate assemblies.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/142
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/187?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/187'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/187'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by PinpointTownes** [comment]
Fantastic! :smile: 

One remark though: you should really try to squash your commits (using `git rebase -i HEAD~[number of commits]`) to avoid making too much noise in the git history.

**Comment by brentschmaltz** [comment]
Thanks!

I agree squashing on such a bit commit is a good thing.
Thanks for the squash lesson.

**Comment by brentschmaltz** [comment]
@PinpointTownes we are going to attempt to rollback, squash and remerge.  Any hints?

**Comment by PinpointTownes** [comment]
Doing that would require rewriting the git history, which is often considered as an evil thing, as it forces everyone who forked/cloned your repository to rebase their copy.

Personally, I completely re-wrote the git history of `AspNet.Security.OpenIdConnect.Server` a few weeks ago: it's clearly a risky operation and you have to be extremely careful if you don't want to loose commits dates.

**Comment by brentschmaltz** [comment]
@PinpointTownes you are correct, we fixed it up Thursday. We learned a lot about squashing, rebasing etc. I was well worth the effort.

@tushargupta51 did most of the heaving lifting, he did a great job.  From now on we think we have enough understanding of git to keep things clean.

Thanks again for the suggestion.

**Pull request merged**
