### PR TITLE
Added the 'x5t' claim to the JwtHeader when the Security Key used is an X509SecurityKey.

### LINKED ISSUE #908: Add 'x5t' claim to JWTHeader when SecurityKey is of type X509SecurityKey
In 4.x we set 'x5t'.
In 5.x we set 'kid'

Some runtimes are expecting one or the other and are broken by this change from 4.x to 5.x.
So we will add both.

### PR DESCRIPTION
**Pull request by mafurman**
Fixes #908.

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@leastprivilege thanks for the heads up. Will think about this.

**Comment by leastprivilege** [comment]
I would rather prefer you fix your old libraries to use kid. And we can get rid of x5t altogether.

**Comment by brentschmaltz** [comment]
@leastprivilege are you asking for a new version of 4x?

**Comment by brentschmaltz** [comment]
@leastprivilege i agree that x5t is a carryover from legacy. 
So if I understand, if 4.x would use the 'kid' you would be fine.

You may want to think about
header["x5t"] = Base64Url.Encode(cert.GetCertHash()));
rather than
header.Add("x5t", Base64Url.Encode(cert.GetCertHash()));

**Comment by brentschmaltz** [comment]
@leastprivilege thanks again for point this out. This would have been a runtime breaking change for users.
We have decided against taking this change.

**Comment by brentschmaltz** [comment]
@leastprivilege this is causing problems with users that are expecting the x5t, some IdentityProviders are expecting the x5t in the ClientCredentials flow.
We will need to add it back.

**Comment by leastprivilege** [comment]
Some?

Then why not add it manually in this case like we do - instead of adding it by default?

**Comment by brentschmaltz** [comment]
@leastprivilege well to be honest, anyone calling into AAD using OAuth ClientCredential flow. AAD doesn't consider the kid, only the x5t.
I am thinking of reintroducing X509SigningCredentials, ctor(X509Certificate2). The JwtHeader will recognize that and add the x5t in this case.
Would that work for you.

I you have a chance, would love your opinion on our new model for JSonWebToken in Microsoft.IdentityModel.Tokens.Jwt. We are moving towards simplifying on consuming and returning JObject. It's early, we want to start small and build up the correct API's.

**Comment by brentschmaltz** [comment]
We re-introduced X509SigningCredentials that adds x5t

**Pull request closed without merging**
