### PR TITLE
reacting to API changes in corefx and updating project.json to latest...

### PR DESCRIPTION
**Pull request by tushargupta51**
… packages #212
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213%23issuecomment-128859134%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213%23issuecomment-129007700%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213%23issuecomment-129592537%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/a02abb1490e51d5e8c5c06f0c32154b9bd26f7f2%23commitcomment-12627885%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213%23issuecomment-128859134%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40brentschmaltz%20%22%2C%20%22created_at%22%3A%20%222015-08-07T23%3A34%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%2C%20%7B%22body%22%3A%20%22Don%27t%20forget%20the%20massive%20naming/packages%20changes%20listed%20here%3A%20https%3A//github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c%5Cr%5Cn%5Cr%5Cn%3E%20System.Security.Cryptography.Encryption%20%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Primitives%5Cr%5CnSystem.Security.Cryptography.Hashing%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Primitives%5Cr%5Cn%5Cr%5Cn%3E%20System.Security.Cryptography.RandomNumberGenerator%20%3D%3E%20System.Security.Cryptography.Algorithms%5Cr%5Cn%5Cr%5Cn%3ESystem.Security.Cryptography.Encryption.Aes%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Algorithms%5Cr%5CnSystem.Security.Cryptography.Hashing.Algorithms%20%20%20%20%3D%3E%20System.Security.Cryptography.Algorithms%5Cr%5CnSystem.Security.Cryptography.DeriveBytes%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Algorithms%5Cr%5Cn%5Cr%5Cn%3E%20The%20RSA%20base%20class%20and%20supporting%20types%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Algorithms%5Cr%5Cn%5Cr%5Cn%3E%20The%20RSACryptoServiceProvider%20class%20and%20additional%20supporting%20types%20%3D%3E%20System.Security.Cryptography.Csp%5Cr%5Cn%5Cr%5Cn%3E%20The%20internal%20RSAOpenSsl%20type%20was%20made%20public%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.OpenSsl%5Cr%5Cn%5Cr%5Cn%3E%20RSACng%20was%20copied%20from%20desktop%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%3E%20System.Security.Cryptography.Cng%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%21%5Bimage%5D%28https%3A//cloud.githubusercontent.com/assets/6998306/9151261/ce1037b4-3dfc-11e5-9c4d-25d093e6606e.png%29%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-08-08T16%3A41%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6998306%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/PinpointTownes%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40brentschmaltz%20updated%20the%20packages%20name.%22%2C%20%22created_at%22%3A%20%222015-08-10T20%3A16%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Commit%20a02abb1490e51d5e8c5c06f0c32154b9bd26f7f2%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/a02abb1490e51d5e8c5c06f0c32154b9bd26f7f2%23commitcomment-12627885%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-08-10T23%3A39%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3172421%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/brentschmaltz%22%7D%7D%5D%2C%20%22title%22%3A%20%22Commit%20a02abb1%20comments%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213#issuecomment-128859134'>General Comment</a></b>
- <a href='https://github.com/tushargupta51'></a> @brentschmaltz
- <a href='https://github.com/PinpointTownes'></a> Don't forget the massive naming/packages changes listed here: https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c
> System.Security.Cryptography.Encryption            => System.Security.Cryptography.Primitives
System.Security.Cryptography.Hashing               => System.Security.Cryptography.Primitives
> System.Security.Cryptography.RandomNumberGenerator => System.Security.Cryptography.Algorithms
>System.Security.Cryptography.Encryption.Aes        => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Hashing.Algorithms    => System.Security.Cryptography.Algorithms
System.Security.Cryptography.DeriveBytes           => System.Security.Cryptography.Algorithms
> The RSA base class and supporting types                            => System.Security.Cryptography.Algorithms
> The RSACryptoServiceProvider class and additional supporting types => System.Security.Cryptography.Csp
> The internal RSAOpenSsl type was made public                       => System.Security.Cryptography.OpenSsl
> RSACng was copied from desktop                                     => System.Security.Cryptography.Cng
image
- <a href='https://github.com/tushargupta51'></a> @brentschmaltz updated the packages name.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by tushargupta51** [comment]
@brentschmaltz

**Comment by PinpointTownes** [comment]
Don't forget the massive naming/packages changes listed here: https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c

> System.Security.Cryptography.Encryption            => System.Security.Cryptography.Primitives
System.Security.Cryptography.Hashing               => System.Security.Cryptography.Primitives

> System.Security.Cryptography.RandomNumberGenerator => System.Security.Cryptography.Algorithms

>System.Security.Cryptography.Encryption.Aes        => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Hashing.Algorithms    => System.Security.Cryptography.Algorithms
System.Security.Cryptography.DeriveBytes           => System.Security.Cryptography.Algorithms

> The RSA base class and supporting types                            => System.Security.Cryptography.Algorithms

> The RSACryptoServiceProvider class and additional supporting types => System.Security.Cryptography.Csp

> The internal RSAOpenSsl type was made public                       => System.Security.Cryptography.OpenSsl

> RSACng was copied from desktop                                     => System.Security.Cryptography.Cng


image

**Comment by tushargupta51** [comment]
@brentschmaltz updated the packages name.

**Pull request merged**
