### PR TITLE
Fixes typo in RenewResponse action in WsTrust 1.3

### PR DESCRIPTION
**Pull request by gislikonrad**
There was a copy-paste error in one of the WsTrust 1.3 actions.

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@gislikonrad I rebased on dev and squashed before I saw your pr, sorry. It is hard to see what your PR was now. Can you re-submit.

**Comment by gislikonrad** [comment]
> @gislikonrad I rebased on dev and squashed before I saw your pr, sorry. It is hard to see what your PR was now. Can you re-submit.

I merged my branch. Now you should be able to see the change. Do you still want me to resubmit the PR?

**Comment by brentschmaltz** [comment]
@gislikonrad thanks for catching this!
Can you reissue the PR to brentsch/wstrust.

thanks again.

**Comment by gislikonrad** [comment]
Sure

**Pull request closed without merging**
