### PR TITLE
Remove perl dependency

### PR DESCRIPTION
**Pull request by keegan-caruso**
Rewrite VerifyResourceUsage in powershell

### CODE REVIEW

**Comment by keegan-caruso** [comment]
Link isn't updating: but here is the new Wilson-PR run that is passing on the changed steps: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1362980&view=results

**Review by kllysng — APPROVED** [review]
Thanks for doing this @keegan-caruso!

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by jmprieur — APPROVED** [review]

**Comment by jmprieur** [comment]
Awesome!

**Pull request merged**
