### PR TITLE
Add ECDsa support in `JsonWebKeyConverter.ConvertFromX509SecurityKey`

### LINKED ISSUE #2217: [Bug] `JsonWebKeyConverter.ConvertFromX509SecurityKey` lies about the Key Type
**Which version of Microsoft.IdentityModel are you using?**
6.32.1

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [x] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

I'm trying to take an X509 certificate and expose it in an endpoint as a JWK.

```csharp
var pemCertificate = new X509Certificate2("./cert/fullchain.pem");
var x509Key = new X509SecurityKey(pemCertificate);

var jwk = JsonWebKeyConverter.ConvertFromX509SecurityKey(x509Key);
```

Assuming an X509 certificate using ECDSA for encryption located at `./cert/fullchain.pem`, example contents:

```
-----BEGIN CERTIFICATE-----
MIIETDCCAzSgAwIBAgISBBhBRWSvdpWBH24VvhmxDYd2MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzA4MTAxMzQ3MzRaFw0yMzExMDgxMzQ3MzNaMDAxLjAsBgNVBAMT
JWNvbnRvc29hdXRocHJvdmlkZXIuYXp1cmV3ZWJzaXRlcy5uZXQwWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAASX3NYFworLvBcrbp/t3fcdgtp0DXjYakMJu5iyUR7I
4ksS/IHdoOyfAM51s5SqSmSq1dvMjMOdcMeqz/vpPsBEo4ICJzCCAiMwDgYDVR0P
AQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMB
Af8EAjAAMB0GA1UdDgQWBBQ3DXYJAZtvPmAonBJlLUeYrjE+ADAfBgNVHSMEGDAW
gBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUH
MAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3Iz
LmkubGVuY3Iub3JnLzAwBgNVHREEKTAngiVjb250b3NvYXV0aHByb3ZpZGVyLmF6
dXJld2Vic2l0ZXMubmV0MBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHW
eQIEAgSB9QSB8gDwAHYAtz77JN+cTbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkA
AAGJ3+rOxAAABAMARzBFAiAj0jvzhpfp7EKaEZpMbMZMRiPBp5njbowphakF6u3J
PwIhAPPEvV0YSgMWv0fkPMVJC4vAydCzRPeFPVDV8O0pEMtHAHYAejKMVNi3LbYg
6jjgUh7phBZwMhOFTTvSK8E6V6NS61IAAAGJ3+rQywAABAMARzBFAiEAl9MMVNDW
Ubt+ZN+KxkWYm54Kwb7JDB8MZectf2lwD4oCICiimCe2szvyYPijOJPuaU3tQPVI
IXHilVEOi8w2Oli8MA0GCSqGSIb3DQEBCwUAA4IBAQCm/r4Rs4EJ1I/J2W8LONLZ
uA87Gg2DI4YLxhNHyEpSTk/MmbontHJ6GcblJg+666PSGM1rRs1G6ZeuBlniG3ag
Sc0KTVphVw4XnLMoP2/gJa1N37QbEIkqkNiZKKEKmRm4cen88JfoIxyiTm6BatTC
35+rSB8Ei2iebPknHiur1wO8cj976rCqT28Mto63+uMhrks1edmtNBvpuGoppNjU
RdSawrzIXYPFnFRyKmd19tQhwWnsudDZRFJa9Y4zsep0FqJgXjcwvupXpYtNSWw0
eqi7DeeqUYJMJxZfTKNNA7PtpwINzTYIXmmuzJY/Wxd1qXVZ5dfVkEO89N8Le3Xa
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----

```

**Expected behavior**
`jwk.Kty` should be `"EC"`.

**Actual behavior**
`jwt.Kty` is `"RSA"`.

**Possible solution**
Seems like `ConvertFromX509SecurityKey` just sets "RSA" as a constant:

image

It should investigate the `X509SecurityKey` to find that out. Investigating `x509Key.Certificate.PublicKey.Oid` yields an ECC oid, so it's not an issue with the X509SecurityKey object.

I might be off base here, but I can't find a different path to convert an X509 cert with an ECDSA key to JWK.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2217.

I think the parameter `representAsRsaKey` should probably be renamed to something else as EC will be supported. I am waiting for your feedback.

### CODE REVIEW

**Comment by joegoldman2** [comment]
@jennyf19 @brentschmaltz this PR is ready to be reviewed.

**Comment by joegoldman2** [comment]
@jennyf19 @brentschmaltz can you please have a look? thank you!

**Comment by joegoldman2** [comment]
Hello! Is there anything you are waiting on before you can begin the review?

**Comment by joegoldman2** [comment]
@brentschmaltz this PR is open for quite some time, can I kindly ask you to review it? Thank you.

**Comment by joegoldman2** [comment]
@keegan-caruso are you able to review this PR please?

**Comment by keegan-caruso** [comment]
@joegoldman2 We'd really like to see tests on functional changes.

Would it be possible to test this flow with an in-memory ECDsa key?

**Comment by joegoldman2** [comment]
I added some unit tests but I might have a conflict with #2377. I'll wait for #2377 to be merged first.

Meanwhile, I think the parameter `representAsRsaKey` should probably be renamed to something else as EC will be supported. Any suggestions?

**Comment by ghost** [comment]
I'm closing this PR in favor of #2377. I decided to merge both PRs because it is simpler to test the fixes.

**Pull request closed without merging**
