### PR TITLE
Upgraded to use netstandard1.6 and make solution compilable and testable in VS2015

### PR DESCRIPTION
**Pull request by dissoupo**
- open Wilson.sln in VS2015
- compile
- open Test Explorer, run all 

You may need to install the latest [.NET Core 1.0.3 SDK](https://www.microsoft.com/net/download/core)

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@dissoupo We can't just upgrade to 1.6, we will need to add an additional target.
When we do add another target, we can fix up some of the crypto issue. So we should take some time and be comprehensive. @PinpointTownes  For example https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/488 will be easy to fix in 1.6.

**Comment by brentschmaltz** [comment]
@dissoupo I created issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/583

**Comment by PinpointTownes** [comment]
> @dissoupo We can't just upgrade to 1.6, we will need to add an additional target.

Yes, please :smile:

**Comment by brentschmaltz** [comment]
@PinpointTownes we will try and get this in 5.2.0 milestone, currently tagged for April 8th release.

**Comment by brentschmaltz** [comment]
@dissoupo I am closing this we now have a net452 and netcore 2.0 targets that works with XUnit.

**Pull request closed without merging**
