### PR TITLE
Avoid dependencies inbox in frameworks & TFM clean-up

### PR DESCRIPTION
**Pull request by ViktorHofer**
Related https://github.com/dotnet/runtime/issues/86671#issuecomment-1561159912

1. Avoid dependencies which are inbox in frameworks (i.e. System.Text.Encoding). That avoids the transitive dependency on these old packages which automatically gets added to the consumer. Many of these packages are obsolete and/or vulnerable and shouldn't be referenced anymore.
2. Update a few conditions that listed all used .NET Framework TFMs and instead of TargetFrameworkIdentifier to condition on the version-less .NET Framework identifier.
3. Remove unused versions from dependencies*.props

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Unfortunately I can't build locally because of the following error (regardless or different versions of PowerShell):

```
PS C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet> .\build.cmd

============================
build.ps1 - parameters
Start Time:      07/11/2023 12:10:02

buildType:                   Debug
dotnetDir:                   c:\Program Files\dotnet
root:                        C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet
runTests:                    YES
failBuildOnTest:             YES
slnFile:                     wilson.sln
runApiCompat:                False
generateContractAssemblies:  False

End Time:      07/11/2023 12:10:02
End build.ps1 - parameters
============================


============================
Environment
Start Time:      07/11/2023 12:10:02

Start Time:      07/11/2023 12:10:02
PSScriptRoot:    C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet
artifactsRoot:   C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet\artifacts
dotnetexe:       c:\Program Files\dotnet\dotnet.exe
msbuildexe:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe
nugetVersion:    3.5.0-rc-1285
releaseVersion:
nugetPreview:

End Time:      07/11/2023 12:10:02
End Environment
============================


============================
VerifyResourceUsage.pl
Start Time:      07/11/2023 12:10:02

>>> Start-Process -Wait -PassThru -NoNewWindow perl C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet\src\VerifyResourceUsage.pl
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\git\azure-activedirectory-identitymodel-extensions-for-dotnet\build.ps1:111 char:30
+ ... ageResult = Start-Process -Wait -PassThru -NoNewWindow perl $root\src ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Comment by ViktorHofer** [comment]
&azp list

**Review by westin-m — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@westin-m any idea how to get CI running and how to fix the build error above? I can't build the repository locally...

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by keegan-caruso — APPROVED** [review]

**Comment by westin-m** [comment]
> @westin-m any idea how to get CI running and how to fix the build error above? I can't build the repository locally...

Do you have perl installed? I ran into the same problem and that was the cause for me.

**Pull request merged**
