### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by aakash1906**
Fix for issue #958 

Sample Test: addressing the issue.,and supporting code fix:

var format = "{ 0} asdf {1} {asdf} {aasdf {{asdf2} {pr} asdf}  {1} asdf3}  asd}f asd{f {{{{proc}o}pond}} {a{1}p}  {{{{asdf}}  {{9{asdf}}";
format = SafeStringFormat(null, format, "", "replaced");
//Output: { 0} asdf replaced {asdf} {aasdf {{asdf2} {pr} asdf}  replaced asdf3}  asd}f asd{f {{{{proc}o}pond}} {areplacedp}  {{{{asdf}}  {{9{asdf}}

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@aakash1906 in general we shy away from using Regex. 
It has been known to bring down servers.
When we do use it, we do so sparingly and always compiled with culture invariant.

**Comment by aakash1906** [comment]
@brentschmaltz So, what do you suggest now. 
Intention is mainly only to avoid exception. Thats why, have put on few lines of code, to detect Format, IndexOutOfRange Exceptions, and tune the input before calling string.Format 
(Because, I was able to get some scenarios where inputs from DocumentRetriever or something contained strings with Curly braces causing FormatException when LogHelper.FormatInvariant is directly used)

Now, shall I change it in a way, to just have a simple try catch around it, with a motto that logging shouldn't cause exceptions?

**Comment by mafurman** [comment]
@aakash1906 We can't use this Regex code in our logging since we are a server component, and logging needs to be fast. Users of our library may need to validate many tokens in a short period of time, so milliseconds matter and we can't have logging slow this process down.

We understand that avoiding format exceptions while logging is important, and we will add in a rule that will check for mismatched braces in our log messages. I've created an issue to track this: #989.

**Comment by brentschmaltz** [comment]
@aakash1906 we took action on your action and introduced a script at build time that checks for parameter validation.

see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/VerifyResourceUsage.pl

**Pull request closed without merging**
