### PR TITLE
Fix comment for OpenIdConnectMessage.CreateLogoutRequestUrl()

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@Kahbazi I'll get this into 5.4.1, we don't push into master.

**Comment by brentschmaltz** [comment]
Triggering a build pipeline: /azp run

**Comment by brentschmaltz** [comment]
@Kahbazi can you issue a PR to dev5x ?

**Comment by Kahbazi** [comment]
Done #1176

**Pull request closed without merging**
