### PR TITLE
Regex should use CultureInvariant. Fix for https://github.com/AzureAD/azure…

### PR DESCRIPTION
**Pull request by brentschmaltz**
…-activedirectory-identitymodel-extensions-for-dotnet/issues/788

### CODE REVIEW

**Comment by brentschmaltz** [comment]
@phkelley can you review?

**Comment by phkelley** [comment]
@brentschmaltz This looks good, but there are two more calls to `Regex.IsMatch` in the method `JwtSecurityTokenHandler.CanReadToken` that we should cover as well.

**Comment by phkelley** [comment]
One other thing - you were asking about how to see the performance difference between `Regex.IsMatch` the static method, and calling `IsMatch` on an instance of the `Regex` class. The easiest way to do this is to set `Regex.CacheSize` to 0 in your test environment.

**Comment by brentschmaltz** [comment]
@phkelley thanks, will add the fix to CanReadtoken.

**Pull request merged**
